"""first migration

Revision ID: 42e34b72b0a9
Revises: af34618c3ede
Create Date: 2024-04-11 16:13:36.747509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42e34b72b0a9'
down_revision: Union[str, None] = 'af34618c3ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    #op.drop_table('scrape')
    #op.drop_index('ix_jobs_id', table_name='jobs')
    #op.drop_table('jobs')
    op.add_column('scrape1', sa.Column('posted_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('scrape1', sa.Column('Location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape1', 'Location')
    op.drop_column('scrape1', 'posted_time')
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey')
    )
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_table('scrape',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('companyNames', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_titles', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='scrape_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scrape_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
